name: Reproducibility test

on: [push, pull_request]

jobs:
  reprotest:
    name: Reproducibility test
    runs-on: ubuntu-24.04

    steps:
      - name: Setup
        run: |
          sudo apt update
          sudo apt install -y libssl-dev pkg-config disorderfs faketime locales-all reprotest
          test -c /dev/fuse || mknod -m 666 /dev/fuse c 10 229
          test -f /etc/mtab || ln -s ../proc/self/mounts /etc/mtab

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install tools
        run: |
          cargo install just

      - name: Reprotest
        run: |
          sudo reprotest --vary=-user_group --build-command 'just npm ci; just npm run build; cargo build --all-features --release' . target/release/warpgate
